language: python
python:
- '2.6'
- '2.7'
- '3.2'
install:
- "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]];then pip install -r py26-requirements.txt; fi"
- pip install -r requirements.txt
- pip install coveralls
script:
- make covercheck
after_success: coveralls
notifications:
  email: false
